### ISSUE TITLE
The Javascript tutorial doesn't work on Mac

### ISSUE THREAD

**Issue by TsuyoshiUshio** [metaparticle-io/package#105]
It cause `/proc/1/cgroup not found`. The issue is fixed alread on this issue/pull request. 

https://github.com/metaparticle-io/package/issues/9

However, the npm package seems not updated. Someone who is doing this tutorial might have a problem on Mac until now.   

https://www.npmjs.com/package/@metaparticle/package

**Comment by brendandburns** [comment]
I'll try to push a new package soon.

**Comment by brendandburns** [comment]
I just pushed `0.3.0` to npm.

**Comment by TsuyoshiUshio** [comment]
Thank you, @brendandburns ! I'll try that!

**Comment by brendandburns** [comment]
Closing since this is fixed (please re-open if you continue to see issues)
