### ISSUE TITLE
Java package build file is missing some dependencies

### ISSUE THREAD

**Issue by georgeharley** [metaparticle-io/package#107]
Using release 0.4.0 on MacOS. 

The Maven file **package/java/pom.xml** is missing a couple of Unit test dependencies. Without them running the `mvn install` command in **package/java** results in a build failure because **package/java/src/test/java/io/metaparticle/test/MetaparticleTest.java** can't compile.
The missing dependencies are for JUnit Jupiter, Mockito, and the PowerMock Mockito API.

**Comment by georgeharley** [comment]
Created PR https://github.com/metaparticle-io/package/pull/109

**Comment by brendandburns** [comment]
Closing this since 109 merged.
