### ISSUE TITLE
Java package tutorial instructions contains some inaccuracies and omits a key point

### ISSUE THREAD

**Issue by georgeharley** [metaparticle-io/package#108]
The instructions for the Java package tutorial needs a bit of an update in order to help things go a bit smoother for the user.

- the value of the `@Package` annotation's `repository` field should not contain the `docker.io` prefix
- in the section on exposing the application on the web the instructions fail to mention that the `@Package` annotation needs to have the `publish` field added with a value of `true`. This is critical to the success of the tutorial as without this field the locally built image doesn't get pushed to Docker Hub and none of the scheduled replica pods can start
- the service that is created on the remote Kubernetes cluster is not a LoadBalancer service but a ClusterIP service. That's fine but the instructions state that the new pods run behind a LoadBalancer service (or words to that effect)

**Comment by georgeharley** [comment]
Created PR https://github.com/metaparticle-io/package/pull/110

**Comment by brendandburns** [comment]
CLosing this since #110 merged.
