### ISSUE TITLE
Java sharding tutorial instructions require updating 

### ISSUE THREAD

**Issue by georgeharley** [metaparticle-io/package#112]
Couple of micro changes needed to the Java sharding tutorial: 

* the `@Package` annotation is missing the `publish=true` field
* the `jarFile` value in the `@Package` annotation does not match the Jar created by the Maven POM

**Comment by brendandburns** [comment]
Thanks if you have a PR, I'd love to see it (otherwise I'll update it myself)

**Comment by georgeharley** [comment]
Hi @brendandburns, no need to do it yourself as PR #113 has already been merged.

**Comment by brendandburns** [comment]
Closing, since the PR w/ the fix is merged.
