### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by apobbati** [metaparticle-io/package#117]
Is there a roadmap published for the MetaParticle project overall?
I would like to help contribute any way I can.

**Comment by brendandburns** [comment]
There are lots of open ideas/issues. One of the most interesting is how to integrate rollouts/upgrades.

Basically, if you see something interesting, feel free to file an issue or markdown to discuss the design...

(and I'll try to get a more formal roadmap together too...)

**Comment by apobbati** [comment]
Thanks! I'll look around.
