### ISSUE TITLE
Links to "Initial Tutorial" generate 404

### ISSUE THREAD

**Issue by martinpeck** [metaparticle-io/package#16]
At the top of this page...

https://metaparticle.io/tutorials/javascript-sharding/

... is a sentence...

`Note, this is an advanced tutorial, please start with the initial tutorial`

...where `initial tutorial` is a link. The link 404s.

The generated link is...

`https://metaparticle.io/tutorials/javascript-sharding/tutorial.md`

... when it should be...

`https://metaparticle.io/tutorials/javascript/`

The same is true for all languages and for each section, so all links back from the "advanced" tutorial to the introduction are broken.

**Comment by christopherhein** [comment]
https://github.com/metaparticle-io/package/pull/7 solves it :)

**Comment by martinpeck** [comment]
Aha! Perfect. Sorry @christopherhein ... I looked through the issues to see if it was already mentioned, but didn't check the PRs.

**Comment by martinpeck** [comment]
So, does this fix the links within the tutorials? If so...how. I'm mostly just curious as it wasn't clear (to me) how the site is being generated from the .md file

**Comment by stealthybox** [comment]
#7 looks unrelated to this issue.

**Comment by stealthybox** [comment]
@martinpeck the site is generated with Hugo from this repo:
https://github.com/metaparticle-io/metaparticle-www

I believe the files you're referencing are in `content/tutorials`.
