### ISSUE TITLE
Support for applications without exposed ports or k8s services

### ISSUE THREAD

**Issue by timfpark** [metaparticle-io/package#27]
It looks like when you use the 'metaparticle' runner that it assumes a service port will be provided when creating the pods:

Successfully tagged timfpark/metaparticle-example:latest
2017/12/08 15:33:11 Service "metaparticle-example" is invalid: spec.ports: Required value
==> Detected container metaparticle-example-3000602432-cqpx8:metaparticle-example-0

and also that a service exists when you exit:

^Cexec: internal error
F1208 15:40:41.905327   31945 mp-compiler.go:122] services "metaparticle-example" not found
goroutine 1 [running]:
github.com/golang/glog.stacks(0xc42045ce00, 0xc4201e00b0, 0x5c, 0xa9)
	/home/bburns/gopath/src/github.com/golang/glog/glog.go:769 +0xa7
github.com/golang/glog.(*loggingT).output(0x20655a0, 0xc400000003, 0xc4201e0000, 0x1fef790, 0xe, 0x7a, 0x0)
	/home/bburns/gopath/src/github.com/golang/glog/glog.go:720 +0x36b
github.com/golang/glog.(*loggingT).printf(0x20655a0, 0xc400000003, 0xc4204c6330, 0x29, 0x0, 0x0, 0x0)
	/home/bburns/gopath/src/github.com/golang/glog/glog.go:655 +0x14f
github.com/golang/glog.Fatalf(0xc4204c6330, 0x29, 0x0, 0x0, 0x0)
	/home/bburns/gopath/src/github.com/golang/glog/glog.go:1148 +0x67
main.main()
	/home/bburns/gopath/src/github.com/metaparticle-io/metaparticle-ast/cmd/compiler/mp-compiler.go:122 +0x438

Is it possible to make this an optional element?  

PS.  Happy to provide a PR if you can point me in the right direction.

**Comment by brendandburns** [comment]
PR would be awesome!  The code is in the metaparticle compiler, approximately here:

https://github.com/metaparticle-io/metaparticle-ast/blob/master/compiler/kubernetes-compiler.go#L272
