### ISSUE TITLE
Create Python Package

### ISSUE THREAD

**Issue by willnewby** [metaparticle-io/package#28]
As it stands, we have nice toy code for metaparticle that runs. Next step is to begin making that useful by building a python package that can be installed, imported and used. I'm currently working on that using these docs: https://packaging.python.org/tutorials/distributing-packages/

**Comment by vbmade2000** [comment]
I think We should add Unit Tests too.

**Comment by brendandburns** [comment]
Awesome, many thanks to both of you!  Perhaps we should file a separate issue for the unit tests so that we can assign it to @vbmade2000 ?

**Comment by willnewby** [comment]
That sounds like a great idea.

---------------
Will Newby
Resident Wizard
Phone: 612.208.3806
Email: willnewby@gmail.com

**Comment by brendandburns** [comment]
This is now done:
https://pypi.python.org/pypi/metaparticle_pkg
