### ISSUE TITLE
Add testing...

### ISSUE THREAD

**Issue by brendandburns** [metaparticle-io/package#3]
The whole library is quite poorly tested, we need better unit testing.

**Comment by vllry** [comment]
Added #24 (Golang tests), I think issues to track each implementation would be easiest to follow.

**Comment by vbmade2000** [comment]
Working on Python UTs.

**Comment by pfongkye** [comment]
hi @brendandburns i would like to write tests for the javascript part using jest if that's ok.

**Comment by brendandburns** [comment]
@pfongkye absolutely, would love some mocha tests there.

**Comment by LeighCiechanowski** [comment]
Hi @brendanburns I would like to add some test for the dotnet code. xUnit okay?

**Comment by brendandburns** [comment]
Yeah xUnit is great. Thanks!

--brendan

________________________________
