### ISSUE TITLE
getting null pointer exception when executing 2nd example in Java tutorial

### ISSUE THREAD

**Issue by kondapally1989** [metaparticle-io/package#36]
following is the exception.
`Exception in thread "main" java.lang.NullPointerException
	at io.metaparticle.Metaparticle.inDockerContainer(Metaparticle.java:19)
	at io.metaparticle.Metaparticle.Containerize(Metaparticle.java:78)
	at io.metaparticle.tutorial.Main2.main(Main2.java:24)`

It is because of METAPARTICLE_IN_CONTAINER is not set as env variable. 
once i set the env variable to false, it is working, i think info regarding this variable has to added to tutorial([tutorial](https://metaparticle.io/tutorials/java/)) like exporting the variable , if it will be further used as environment variable. 

can't we use System.getProperty("METAPARTICLE_IN_CONTAINER"); instead of System.getenv("METAPARTICLE_IN_CONTAINER"); in metaparticle.java
if we use property, we can pass it as args or we can also set using System.setProperty();
or am i making wrong assumptions.

**Comment by brendandburns** [comment]
Closed by #47
