### ISSUE TITLE
Ability to customize Dockerfile

### ISSUE THREAD

**Issue by radu-matei** [metaparticle-io/package#53]
Briefly mentioned this in #50, but I think it deserves its own issue.

Right now as I looked around the packaging, when writing an application you cannot customize the Dockerfile in any way - would it make sense to allow it as a parameter?

I am not saying it should be default, but once the needs of the service overcome what is included in the basic Dockerfile for each runtime, then it might be useful to allow (either in code or as separate file) to come with your own Dockerfile.

Looking at #2 - does it only refer to adding files from the project?
How would you handle external deps?

Radu M

**Comment by stealthybox** [comment]
related: #51 
java/js/python/dotnet now support copying a dockerfile from somewhere on the file system.

**Comment by brendandburns** [comment]
yeah #51 should address this.

re #2 thats to pull in other files (eg static html, etc)

**Comment by brendandburns** [comment]
Closing this since #51 covers this.
