### ISSUE TITLE
Service Dependencies

### ISSUE THREAD

**Issue by srini85** [metaparticle-io/package#73]
Typically, when we develop a project, we reference libraries and other projects into our source code and then compile them. In dotnet land, the references are located in the csproj file and we pull them from nuget sources. 

Now in the distributed computing world, we ideally have loosely coupled services without direct dependencies to other services. However there could be those occasions where one service does depend on another service. If we use the [kubernetes services example](https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/), we may  write a service that depends on nginx being available in the cluster as it may wish to offload some requests to that service. 

This brings up the question as to whether there should be a need for metaparticle to have some smarts to enable users to build up their service dependencies in code, or is it wrong architecturally to have this dependency in the first place? If the former is true, should we be checking whether _a service/collection of services_ is reachable when you run your application?

**Comment by brendandburns** [comment]
Right now, I'm targetting Metaparticle at individual microservices.  I don't really want to try to handle too much in the way of dependencies beyond string names.

But some sort of integration of the Open Service Broker might be interesting...

**Comment by brendandburns** [comment]
closing this since I think the discussion on this issue is completed.  Please re-open if there is more to discuss.

Thanks!
