### ISSUE TITLE
Support for macOS Development

### ISSUE THREAD

**Issue by christopherhein** [metaparticle-io/package#9]
I think this belongs more in this repo - https://github.com/metaparticle-io/metaparticle-ast/issues/2 based on https://github.com/metaparticle-io/package/blob/master/javascript/metaparticle-package/index.js#L5-L18

**Comment by chanezon** [comment]
You're right, the bug is in this repo. This PR helped me to make it work with Docker for Mac.

**Comment by brendandburns** [comment]
This is now fixed (I think)
