### ISSUE TITLE
Python sample does not (appear to) support "public: True"

### ISSUE THREAD

**Issue by DazWilkin** [metaparticle-io/package#92]
Context: https://github.com/metaparticle-io/package/issues/82

It's unclear to me where I should specific `'public': True' in the Python library in order to get a network LB programmed.

Using the Python sample summarized in that issue, succeeds with a K8s Deployment but the Service created exposes a ClusterIP. Per @brendanburns suggestion, there appears no support for `"public: True"` in the Python code but I am likely wrong.

Including
```Python
runtime={
  ...
  'public': True
  ...
}
```
results:

`Unexpected option(s) provided: __new__() got an unexpected keyword argument 'public'`

There are 2 Python implementations of metaparticle in the repo.

I'm using the one under `package\python\metaparticle_pkg` and the `options.py` specifies:

`class RuntimeOptions(namedtuple('Runtime', 'executor replicas ports publicAddress shardSpec jobSpec')):`

This appears (!?) to exclude an option for `public`.

I tried `publicAddress` with a static IP but that does not work either.

The Python code *does* generate 3 metaparticle configuration files:

```
[[NAME]]-deploy.json
[[NAME]]-load-balancer.json
spec.json
```
The `-load-balancer.json` omits `type: LoadBalancer` probably due to the fact that I'm not able to specify `'public': True` in the `runtime` config :
```JSON
{
  "metadata": {
    "name": "[[NAME]]",
    "creationTimestamp": null
  },
  "spec": {
    "ports": [
      {
        "protocol": "TCP",
        "port": 8080,
        "targetPort": 0
      }
    ],
    "selector": {
      "app": "mp-python"
    }
  },
  "status": {
    "loadBalancer": {}
  }
}
```

**Comment by brendandburns** [comment]
I believe that it is called `publicAddress`:

https://github.com/metaparticle-io/package/blob/master/python/metaparticle_pkg/option.py#L24

Which is perhaps the wrong name for it, since it is inconsistent...

**Comment by brendandburns** [comment]
This is now fixed, the correct syntax is:

```python
...
runtime={'ports': [8080], 'executor': 'metaparticle', 'replicas': 3, 'public': True}
...
```

**Comment by DazWilkin** [comment]
Still no joy :-(

The container generates a stacktrace ([see](#stacktrace)).

After an absence [btw: metaparticle.io is down] -- I tried again but continue to be unsuccessful with the Python implementation. I'm bothered that it's me. However, I've been successful with JavaScript and Golang (and should perhaps stick to them).

```
git clone https://github.com/metaparticle-io/package.git
git fetch origin 0bf29e17b9ce6d472f1fb06ffb8271b557569258
cd python/examples/web
```
Edited `requirements.txt`:
```
six==1.10.0
metaparticle_pkg>=0.6.6
```
Edited `web.py`:
```
@Containerize(
    package={
        "name": name,
        "repository": repo,
        "publish": True,        # <--- Was missing
    },
    runtime={
        "ports": [port],
        "executor": "metaparticle",
        "replicas": 3,
        "public": True,
    }
)
```
### <a name="stacktrace"></a>Stacktrace
The image generates the following error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/docker/transport/unixconn.py", line 46, in connect
    sock.connect(self.unix_socket)
FileNotFoundError: [Errno 2] No such file or directory
```
On my local machine in the virtualenv:
```
pip freeze
backports.ssl-match-hostname==3.5.0.1
certifi==2018.1.18
chardet==3.0.4
docker==2.7.0
docker-pycreds==0.2.2
idna==2.6
ipaddress==1.0.19
metaparticle-pkg==0.6.6
requests==2.18.4
six==1.10.0
urllib3==1.22
websocket-client==0.47.0
```

**Comment by gabeduke** [comment]
I have the same error. What OS are you running? I'm on Linux, but another user ran the same code from Mac and it worked.

**Comment by DazWilkin** [comment]
Yep, Linux (Debian).

**Comment by DazWilkin** [comment]
Evidence suggests something with the Python-Docker bridge on Linux.

On the same machine:
-- I can run the Python sample same-same without the 'Containerize' decorator. No Docker.
-- I can run e.g. the Golang samples in Docker.

As is to be expected, I receive the same error regardless of where the Docker image is run: a remote Kubernetes Engine cluster (CoreOS) or my local Debian workstation.

```
docker --version
Docker version 17.09.0-ce, build afdb6d4
```
