### ISSUE TITLE
Suggestion: Using Google Container Registry

### ISSUE THREAD

**Issue by DazWilkin** [metaparticle-io/package#93]
If you're using Google Cloud Platform (GCP) and/or Kubernetes Engine and/or prefer to use [Google Container Registry](cloud.google.com/container-registry) (GCR), absent a specific GCR builder, it is possible to authenticate a docker client|CLI against GCR and then use GCR  (gcr.io) transparently instead of docker.io

For example, my Docker Hub is `docker.io/dazwilkin` and customarily:

`echo $PASSWORD | docker login --username=dazwilkin --password-stdin https://docker.io`

GCR is GCP-project specific. You can authenticate the docker client to your project's GCR with:

```
PASSWORD=$(gcloud auth application-default print-access-token)
docker login \
  --username=oauth2accesstoken \
  --password=${PASSWORD} \
  https://gcr.io
```

Then `docker` registry-related commands are effective against the specified (see below) GCP-project registry. For example, I then replace:

`repository: "docker.io/dazwilkin"`

With the value of my desired GCP Project ID `[[PROJECT-ID]]`:

`repository: "gcr.io/[[PROJECT-ID]]"`

If you're using containers on GCP, this provides simpler security and better network performance.

See:
https://cloud.google.com/container-registry/docs/advanced-authentication#using_an_access_token
https://medium.com/google-cloud/google-container-registry-4aca1fc6cf74

**Comment by xfernando** [comment]
@DazWilkin I just added a pull request documenting how to access GCR and ACR with metaparticle's go package. :)

**Comment by DazWilkin** [comment]
@xfernando Nice!! 👍
